# Generated by Django 6.0.5 on 2026-05-12 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publications', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='photographe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='users.profilphotographe'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='publications.publication'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('utilisateur', 'publication')},
        ),
    ]
