# Generated by Django 4.2.30 on 2026-05-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_categorie_tag_alter_publication_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='image_url',
        ),
        migrations.AddField(
            model_name='publication',
            name='est_vendue',
            field=models.BooleanField(default=False, help_text='True quand la photo a été achetée — le filigrane est retiré.'),
        ),
        migrations.AddField(
            model_name='publication',
            name='image_filigrane',
            field=models.ImageField(blank=True, null=True, upload_to='publications/filigranes/'),
        ),
        migrations.AddField(
            model_name='publication',
            name='image_originale',
            field=models.ImageField(blank=True, null=True, upload_to='publications/originales/'),
        ),
    ]
