# Generated by Django 4.2.30 on 2026-05-24 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversations', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-last_message_at']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['sent_at']},
        ),
        migrations.AddField(
            model_name='message',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='conversations/fichiers/'),
        ),
        migrations.AddField(
            model_name='message',
            name='nom_fichier_original',
            field=models.CharField(blank=True, help_text="Nom du fichier tel qu'envoyé par l'utilisateur.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='type_fichier',
            field=models.CharField(blank=True, help_text='MIME type du fichier (ex: image/jpeg, application/pdf).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='contenu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='expediteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL),
        ),
    ]
