# Generated by Django 4.2.30 on 2026-05-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profilphotographe_photo_couverture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilphotographe',
            name='essai_utilise',
            field=models.BooleanField(default=False, help_text='True si le photographe a déjà utilisé son essai gratuit.'),
        ),
    ]
