# Generated by Django 4.2.30 on 2026-05-16 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_remove_publication_image_url_publication_est_vendue_and_more'),
        ('commandes', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='commande',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='articles', to='publications.publication'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('annule', 'Annulé')], default='en_attente', max_length=20),
        ),
    ]
