# Generated by Django 6.0.5 on 2026-05-12 16:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expiré', 'Expiré'), ('annulé', 'Annulé')], default='active', max_length=20)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_deb', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
