# Generated by Django 4.2.30 on 2026-05-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abonnement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='abonnement',
            name='duree',
            field=models.CharField(choices=[('1_mois', '1 mois'), ('3_mois', '3 mois'), ('6_mois', '6 mois')], default='1_mois', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expire', 'Expiré'), ('annule', 'Annulé')], default='active', max_length=20),
        ),
    ]
