# Generated by Django 4.2.30 on 2026-05-15 11:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0003_alter_abonnement_options_abonnement_duree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='duree',
            field=models.CharField(choices=[('1_mois', '1 mois'), ('3_mois', '3 mois'), ('6_mois', '6 mois')], default='1_mois', max_length=10),
        ),
        migrations.CreateModel(
            name='PlanTarif',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium')], max_length=20)),
                ('duree', models.CharField(choices=[('1_mois', '1 mois'), ('3_mois', '3 mois'), ('6_mois', '6 mois')], max_length=10)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('est_actif', models.BooleanField(default=True, help_text='Décocher pour masquer ce tarif sans le supprimer.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan tarifaire',
                'verbose_name_plural': 'Plans tarifaires',
                'ordering': ['plan', 'duree'],
                'unique_together': {('plan', 'duree')},
            },
        ),
        migrations.AddField(
            model_name='abonnement',
            name='plan_tarif',
            field=models.ForeignKey(help_text='Tarif appliqué au moment de la souscription.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonnements', to='abonnements.plantarif'),
        ),
    ]
