# Generated by Django 4.2.30 on 2026-05-24 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abonnements', '0004_alter_abonnement_duree_plantarif_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suivi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suiveur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to=settings.AUTH_USER_MODEL)),
                ('suivi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('suiveur', 'suivi')},
            },
        ),
    ]
