# Generated by Django 4.2.30 on 2026-09-03 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('like_publication', 'Like sur une publication'), ('like_commentaire', 'Like sur un commentaire'), ('nouveau_suivi', 'Nouveau abonné'), ('reponse_commentaire', 'Réponse à un commentaire')], max_length=30)),
                ('message', models.CharField(max_length=255)),
                ('publication_id', models.UUIDField(blank=True, null=True)),
                ('commentaire_id', models.UUIDField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text="False quand l'utilisateur supprime la notification.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('declencheur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_declenchees', to=settings.AUTH_USER_MODEL)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
